### ISSUE TITLE
Add a group_id to related building outlines

### ISSUE THREAD

**Issue by YingtingChen** [linz/nz-building-outlines#148]
### Bug Description

Link between related building outlines is missing. For example, the outlines below are recorded as 
2033 -- 1032
2033 -- 1033
2032 -- 1032
where the separated outlines 2032 and 1033 are not related in the table.

- Need to change test data.
 - Need to change the comparison script - sql

#### Screenshots
![image](https://user-images.githubusercontent.com/33814626/45005313-bf63fb00-b046-11e8-8864-9000a0bec753.png)

**Comment by dwsilk** [comment]
The link will be created by adding a related_group_id rather than directly linking the features that don't overlap.

**Comment by YingtingChen** [comment]
Missing relationship was added along with the related_groups changes in the PR #149
