### ISSUE TITLE
Manually investigate the imagery overlap issues

### ISSUE THREAD

**Issue by charlottedawson** [linz/nz-building-outlines#159]
### User Story

In order to have a consistent process for B.Outline QA as an LDA I need to figure out the inconsistencies for Canterbury capture.

## Acceptance Criteria

- [x] Find out which imagery the buildings actually align to 
- [x] Look at improving the process for future QA
- [x] Do NOT hit compare

**Comment by jducnuigeen** [comment]
The buildings IN RED inside the yellow highlight match the Canterbury 0.4m Rural 2012-2013 imagery. The light blue buildings match the Canterbury 0.4m Rural 2013-2014 imagery. Interestingly, when I loaded the "existing_subset_extracts" table from the database (the red buildings) there also were some building in the south which is marked by the red circle.
![image](https://user-images.githubusercontent.com/25912064/47692818-f7a94380-dc5b-11e8-8ba5-04fe081101f8.png)

**Comment by jducnuigeen** [comment]
Discussion with Paul also highlighted that we'll need to include process for checking rural areas that there are no new buildings which might be rock outcroppings, especially in mountainous or remote valley areas. I already found some, but Daniel mentioned we'll take care of all of these in one go. Paul mentioned we should check against existing Huts, shelters, private huts, fire lookouts, camps, and lodge from the building points dataset, as well as bivouacs from the bivouac dataset.
