### ISSUE TITLE
Update capture source areas to fix the overlap issue

### ISSUE THREAD

**Issue by YingtingChen** [linz/nz-building-outlines#162]
### User Story

In order to a consistent process for Building Outline QA as a LDA I want to update capture source areas.
 
#### Acceptance Criteria
- [ ] Fix the area boundary by which imagery the buildings actually align to.
- [ ] Identify other problems.
- [ ] Save updated files to S:

**Comment by YingtingChen** [comment]
Updated capture source area: 

Waikato rural 12-13:

![image](https://user-images.githubusercontent.com/33814626/47825536-6363eb80-ddd7-11e8-8b95-7c2d8622602e.png)
Cyan color polygon is the updated boundary which is clipped by Waikato urban and Hawkes Bay.

Canterbury rural 12-13:

![image](https://user-images.githubusercontent.com/33814626/47825723-4bd93280-ddd8-11e8-8b28-967dea7473b4.png)

Canterbury rural 13-14

![image](https://user-images.githubusercontent.com/33814626/47825808-edf91a80-ddd8-11e8-99d4-83d0f92c495e.png)

**Comment by YingtingChen** [comment]
Errors found:

- [ ] Some of the building outlines in Wellington are out of the imagery. Should remove those outlines
- [ ] The Christchurch tiles might not be clipped when create the imagery surverys dataset.
![image](https://user-images.githubusercontent.com/33814626/47826003-fc940180-ddd9-11e8-8060-4630307d06a0.png)

**Comment by Ben-Cheng** [comment]
Some updates on the Christchurch 0.075m Urban Aerial Photos Index Tiles (2015-2016).
I failed to create the survey extent of the index tiles, I think there is a bug in raster calculator? Not sure yet but will look into it.

Currently the raster calculator does not calculate this specific layer correctly, have tried other layers and worked fine.

**Comment by YingtingChen** [comment]
Changes above have been added to S:\IndependentDatasets\BuildingOutlines\ReferenceData\updated_capture_source_area\
