### ISSUE TITLE
Check that docs location works when this repo is public

### ISSUE THREAD

**Issue by jducnuigeen** [linz/nz-building-outlines#56]
### User Story

As a user I want building outlines ReadTheDocs documentation to fully describe the dataset, and have as much of of this documentation automatically generated. Currently the testing and setup of our ReadTheDocs pages are on a personal repo. This needs to be transferred to a LINZ repo and all elements/pages transferred and tested, along with potential need to setup the LINZ domain and connect it with ReadTheDocs.

#### Acceptance Criteria
- [x] ~~Find out if we have an existing ReadTheDocs LINZ account, and if so, determine method to allow ReadTheDocs to use the LINZ domain name for this data set.~~
- [x] Once we know final location for the building outlines documentation, transfer test data elements to correct repo and  LINZ's ReadTheDocs account.

**Comment by dwsilk** [comment]
Working public docs at: https://nz-building-outlines.readthedocs.io/en/latest/index.html
