### ISSUE TITLE
Run pre load QA checks on all supplied buildings datasets

### ISSUE THREAD

**Issue by charlottedawson** [linz/nz-building-outlines#92]
### User Story

In order to add data to the NZ Building Outlines dataset, as a location data analyst I want QA checks (valid geometry / location etc) carried out.

#### Acceptance Criteria
- [ ] all topo utility checks are executed
- [ ] any issues that need to be resolved are documented

**Comment by dwsilk** [comment]
@YingtingChen has run initial checks on 4 supplied datasets. Common issues were:

#### 1. Interior rings not within exterior rings

![image 3](https://user-images.githubusercontent.com/8953184/40592846-e2cadc2a-6277-11e8-9deb-21932fb70b40.png)
![pasted image at 2018_05_24 09_54 am](https://user-images.githubusercontent.com/8953184/40592849-e528d8dc-6277-11e8-8c24-997ebc8c74ed.png)

#### 2. Very close / duplicate nodes

Sometimes this also involves self-intersection:

![image 4](https://user-images.githubusercontent.com/8953184/40592860-ff304a30-6277-11e8-927b-da0778e8cbd2.png)

These are to be fixed before data is uploaded into PostgreSQL / PostGIS.

**Comment by YingtingChen** [comment]
This is actually a multi-part polygon, where the larger part has one inner ring and the smaller has 0. The problem is these two parts have segments intersect with each other.
Buildings like this will be identified with the **Interior rings not within exterior rings** problem
![image](https://user-images.githubusercontent.com/33814626/40593332-0d89235a-627c-11e8-9325-7c11834b4c0c.png)

**Comment by dwsilk** [comment]
Oh okay - so multiple exterior rings when we enforce only 1 by using `Polygon` geometry type.

**Comment by YingtingChen** [comment]
Both the `building_outlines` (all datasets after check_validity) and `QA_Check results` zip files are being uploaded (should finish uploading tonight) to google drive: [click link](https://drive.google.com/open?id=1U_b-rG4qJoWPedzd8sDxDRemyourWwXc)

The QA checks include:

- QA_Building_Overlaps
- QA_Small_Buildings (area less than 10m2)
- QA_Buildings_With_Multiple_Exteior_Rings
- QA_Buildings_Not_Within_Coastline
- QA_Buildings_Overlap_River_Centrelines
- QA_Buildings_Overlap_River_Polygons
- QA_Buildings_Overlap_Lake_Polygons
- QA_Buildings_Overlap_Swamp_Polygons
- QA_Buildings_Overlap_Pond_Polygons
- QA_Buildings_Overlap_Lagoon_Polygons
- QA_Buildings_Overlap_Canal_Centrelines
- QA_Buildings_Overlap_Canal_Polygons

No `Multiple_Exteior_Rings` feature was found in the datasets

**Comment by dwsilk** [comment]
Completed
