### ISSUE TITLE
Add all building outlines data into S: folder.

### ISSUE THREAD

**Issue by charlottedawson** [linz/nz-building-outlines#96]
### User Story

In order to upload data to the database, as a location data analyst I want all of the building outline data in the corporate environment in a consistent folder structure.

#### Acceptance Criteria
- [x] All previously supplied Building Outline datasets in S:\IndependentDatasets\BuildingOutlines\SuppliedData
- [x] Datasets are split up so that they all relate to only one aerial imagery capture source

**Comment by charlottedawson** [comment]
Data on HD

**Comment by charlottedawson** [comment]
![image](https://user-images.githubusercontent.com/15007775/40525432-12c9b798-6034-11e8-8243-934147c6c286.png)
Coverage map

**Comment by dwsilk** [comment]
@charlottedawson so this is done?
