### ISSUE TITLE
Update specific details in Data Dictionary

### ISSUE THREAD

**Issue by charlottedawson** [linz/nz-building-outlines#97]
### User Story

In order to have consistent Data Dictionary as a LDS user I want all links and references in the Building Outlines dataset to be correct.

#### Acceptance Criteria
- [ ] Update link on `Published Data` page to the new LDS web link for Building dataset.
- [x] Update the `Source Imagery` section with correct links to the Imagery Surveys data/data dictionary.
- [x] Update the schema diagram

**Comment by jducnuigeen** [comment]
Schema Diagram updated.
However, we don't yet know the unique ID code for the dataset URL, and hence can't update the "Published Data" page URL link until we do. Vicky says that unique number isn't known until the first time the dataset is published.

I'll create a pull request for the diagram at least.
