### ISSUE TITLE
Data Dictionary: Figures resize issues; fix site URL path

### ISSUE THREAD

**Issue by jducnuigeen** [linz/nz-building-outlines#99]
### User Story

In order to have readable database diagrams in the Data Dictionary, the figures should not resize without scaling when the browser page width is reduced. Clicking the image for the diagram should allow the use to see a larger image with a more clear view of the components.
When the live building outlines repo is made public, the URL for linking will change, and only one line in the conf.py should need to be changed.

#### Acceptance Criteria
- [x] Changing the browser window size changes the size of the image in a scaled way, rather than having width and height scaled independently.
- [x] Change the lines which hard code the URL for the site

**Comment by dwsilk** [comment]
Fixed by #104
